
from http.cookies import CookieError
from django.db import models

# Create your models here.

class Ocs_Recharge(models.Model):
    ID = models.BigAutoField(primary_key=True)
    ip =models.CharField(max_length=200)
    lable1 =models.CharField(max_length=200)
    lable2  =models.CharField(max_length=200)       
    lable3 =models.CharField(max_length=200)
    lable4=models.CharField(max_length=200)
    lable5=models.CharField(max_length=200)
    data_start=models.DateTimeField() 
    lable7 =models.CharField(max_length=200)     
    lable8 =models.CharField(max_length=200)    
    lable9 =models.CharField(max_length=200)    
    lable10=models.CharField(max_length=200)     
    lable11 =models.CharField(max_length=200)         
    lable12 =models.CharField(max_length=200)        
    lable13 =models.CharField(max_length=200)
    lable14=models.CharField(max_length=200)
    lable15 =models.CharField(max_length=200)
    lable16 =models.CharField(max_length=200)         
    lable17 =models.CharField(max_length=200)         
    lable18=models.CharField(max_length=200)
    lable19 =models.CharField(max_length=200)         
    lable20=models.CharField(max_length=200)
    lable21=models.CharField(max_length=200)
    lable22 =models.CharField(max_length=200)
    lable23 =models.CharField(max_length=200)
    lable24 =models.CharField(max_length=200)
    lable25 =models.CharField(max_length=200)
    lable26 =models.CharField(max_length=200)
    lable27 =models.CharField(max_length=200)
    lable28=models.CharField(max_length=200)
    lable29=models.CharField(max_length=200)
    lable30=models.CharField(max_length=200)
    lable31=models.CharField(max_length=200)
    profile_etudiant=models.CharField(max_length=200)
    adresse_ip=models.CharField(max_length=200)
    lable34=models.CharField(max_length=200)
    lable35=models.CharField(max_length=200)
    lable36=models.CharField(max_length=200)
    lable37=models.CharField(max_length=200)
    lable38=models.CharField(max_length=200)
    lable39=models.CharField(max_length=200)
    lable40=models.CharField(max_length=200)
    lable41=models.CharField(max_length=200)
    lable42 =models.CharField(max_length=200)
    lable43=models.CharField(max_length=200)
    lable44=models.CharField(max_length=200)
    lable45 =models.CharField(max_length=200) 
    lable46=models.CharField(max_length=200)
    lable47=models.CharField(max_length=200)           
    lable48=models.CharField(max_length=200)
    lable49=models.CharField(max_length=200) 
    lable50=models.CharField(max_length=200)
    list_balance=models.CharField(max_length=2000)   
    subscriber=models.CharField(max_length=200)       
    sublable=models.CharField(max_length=200)
    sublable1 =models.CharField(max_length=200)
    sublable2 =models.CharField(max_length=200)
    sublable3 =models.CharField(max_length=200)
    sublable4 =models.CharField(max_length=200)
    sublable5=models.CharField(max_length=200)
    sublable6=models.CharField(max_length=200)
    sublable7 =models.CharField(max_length=200)
    list_update=models.CharField(max_length=2000)

"""
######################################################### Deuxieme table 
"""
class Ocs_Voix(models.Model):
    ID =models.BigAutoField(primary_key=True)
    id =models.CharField(max_length=20)
    lable1=models.CharField(max_length=200)
    lable2=models.CharField(max_length=200)       
    lable3=models.CharField(max_length=200)
    lable4=models.CharField(max_length=20)
    lable5=models.CharField(max_length=20)
    start_time=models.DateTimeField() 
    end_time=models.DateTimeField()
    call_read=models.CharField(max_length=200)   
    billed_duration=models.CharField(max_length=200)      
    lable10=models.CharField(max_length=200)     
    lable11=models.BigIntegerField()         
    lable12=models.BigIntegerField()       
    lable13=models.BigIntegerField()   
    traffic_type=models.CharField(max_length=200)
    traffic_sous_type=models.CharField(max_length=200)
    lable16=models.IntegerField()         
    lable17=models.CharField(max_length=200)         
    lable18=models.FloatField()
    lable19=models.FloatField()        
    lable20=models.IntegerField()
    lable21=models.CharField(max_length=200)
    lable22=models.CharField(max_length=200)
    lable23=models.CharField(max_length=200)
    lable24=models.CharField(max_length=200)
    lable25=models.CharField(max_length=200)
    lable26=models.IntegerField()
    lable27=models.IntegerField()
    lable28=models.CharField(max_length=200)
    lable29=models.IntegerField()
    lable30=models.IntegerField()
    lable31=models.IntegerField()
    profile=models.CharField(max_length=200)
    charging_server_ip=models.CharField(max_length=200)
    ip_trunk_used=models.CharField(max_length=200)
    lable35=models.BigIntegerField()
    lable36=models.CharField(max_length=200)
    lable37=models.CharField(max_length=200)
    lable38=models.CharField(max_length=200)
    lable39=models.CharField(max_length=200)
    lable40=models.CharField(max_length=200)
    lable41=models.CharField(max_length=200)
    lable42=models.CharField(max_length=200)
    lable43=models.CharField(max_length=200)
    lable44=models.CharField(max_length=200)
    lable45=models.CharField(max_length=200) 
    lable46=models.CharField(max_length=200)
    lable47=models.CharField(max_length=200)           
    lable48=models.CharField(max_length=200)
    lable49=models.IntegerField()
    lable50=models.IntegerField()
    list_balance=models.CharField(max_length=2000)   
    lable69=models.CharField(max_length=200)       
    lable70=models.CharField(max_length=200)
    lable71=models.CharField(max_length=200)
    lable72=models.CharField(max_length=200)
    lable73=models.CharField(max_length=200)
    lable74=models.CharField(max_length=200)
    lable75=models.CharField(max_length=200)
    lable76=models.CharField(max_length=200)
    lable77=models.CharField(max_length=200)
    lable78=models.CharField(max_length=200)
    lable79=models.CharField(max_length=200)       
    lable80=models.CharField(max_length=200)
    lable81=models.CharField(max_length=200)
    lable82=models.CharField(max_length=200)
    lable83=models.CharField(max_length=200)
    lable84=models.CharField(max_length=200)
    lable85=models.CharField(max_length=200)
    lable86=models.CharField(max_length=200)
    lable87=models.CharField(max_length=200)
    lable88=models.CharField(max_length=200)
    lable89=models.CharField(max_length=200)
    lable90=models.CharField(max_length=200)
    lable91=models.CharField(max_length=200)
    lable92=models.CharField(max_length=200)
    lable93=models.CharField(max_length=200)
    lable94=models.CharField(max_length=200)
 
"""
######################################################### trosieme table 

"""

class MZ_topup(models.Model):
    ID =models.BigAutoField(primary_key=True)
    msisdn_mobile=models.CharField(max_length=200)
    comman_contend=models.CharField(max_length=200)
    update_date=models.DateTimeField()
    action_type=models.IntegerField()
    status=models.IntegerField()
    code  =models.IntegerField()
    fee=models.IntegerField()
    etat=models.CharField(max_length=20)
    create_date=models.DateTimeField()
    username=models.CharField(max_length=20)
    ip_adress=models.CharField(max_length=20)
    quantite_data=models.CharField(max_length=20)
    quantite_voix=models.CharField(max_length=20)
    quantite_balance_principale=models.CharField(max_length=20)
    fee_calculated=models.IntegerField()
    type_package=models.CharField(max_length=200)
    auto_recharge=models.CharField(max_length=200)
    msisdn_fixe=models.BigIntegerField()
    package=models.CharField(max_length=200)
    canneaux=models.CharField(max_length=200)
    