# Generated by Django 4.0.6 on 2022-08-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_mz_topup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MZ_topup',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('msisdn_mobile', models.CharField(max_length=200)),
                ('comman_contend', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField()),
                ('action_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('code', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('etat', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('username', models.CharField(max_length=20)),
                ('ip_adress', models.CharField(max_length=20)),
                ('quantite_data', models.CharField(max_length=20)),
                ('quantite_voix', models.CharField(max_length=20)),
                ('quantite_balance_principale', models.CharField(max_length=20)),
                ('fee_calculated', models.IntegerField()),
                ('type_package', models.CharField(max_length=200)),
                ('auto_recharge', models.CharField(max_length=200)),
                ('msisdn_fixe', models.BigIntegerField()),
                ('package', models.CharField(max_length=200)),
                ('canneaux', models.CharField(max_length=200)),
            ],
        ),
    ]
